- name: test variables...
  hosts: proxy.local
  vars:
    - app_port: "1234"
  gather_facts: no
  tasks:
    - debug: msg="{{ hostvars }}"
    - debug: msg="hostvars={{ hostvars }}"
    - debug: msg="vars={{ vars }}"
    - debug: msg="groups={{ groups }}"
    - debug: msg="{{ app_port }}"
    - debug: msg="{{ item }}"
      with_items: groups.appservers
    - debug: msg="{{ groups.appservers }}"
    - debug: msg="{{ groups.proxies }}"
    - debug: msg="{{ groups.dbservers }}"
