---

- name: add my.cnf via template
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: restart mysql
  tags:
    - db

- name: Add {{ mysql_user }}
  mysql_user:
    name="{{ mysql_user }}"
    password="{{ mysql_user_password }}"
    login_user=root
    login_password=''
    state=present
    priv=*.*:ALL
    host={{ item }} priv=*.*:ALL
  with_items:
    - localhost
    - '%'
  tags:
    - db

- name: add {{ mysql_user }} database
  mysql_db:
    name="{{ mysql_user }}"
    state=present
    login_user="{{ mysql_user }}"
    login_password="{{ mysql_user_password }}"
  tags:
    - db

