---

- name: Create {{ group }}
  group: name={{ group }}

- name: Create {{ user }} account
  user:
    name={{ user }}
    comment="{{ user_name }}"
    group={{ group }}
    groups=sudo
    createhome=yes
    home=/home/{{ user }}
    shell=/bin/bash
    password={{ password }}
    state=present

- name: ensure ssh directory exists for {{ user }}
  file:
    dest=/home/{{ user }}/.ssh
    owner={{ user }}
    group={{ group }}
    state=directory
    mode=0700

- name: ensure public key is in authorized_keys
  lineinfile:
    dest=/home/{{ user }}/.ssh/authorized_keys
    state=present
    line="{{ lookup('file','~/.ssh/id_rsa.pub') }}"
    insertafter=EOF
    create=yes
    owner={{ user }}
    group={{ group }}
    mode=600
    regexp=^WILL_NOT_MATCH

