---

- name: Update apt keys
  command: apt-key update
  tags:
    - apt

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - apt

- name: Upgrade apt cache
  apt: upgrade=yes
  tags:
    - apt

- name: ensure installed vim
  apt:
    pkg=vim
    state=present
    update_cache=no

- name: set filetype indent off
  lineinfile:
    dest=/etc/vim/vimrc
    line='filetype indent off'
    state=present
