---

- name: Update /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp=".*{{ item.hostname }}$"
    line="{{ item.ip }} {{ item.hostname }}.local {{ item.hostname }}"
    state=present
  when:
    ansible_eth1.ipv4.address != "{{ item.ip }}"
  with_items:
    - { ip: '192.168.101.10', hostname: 'db' }
    - { ip: '192.168.101.11', hostname: 'app1' }
    - { ip: '192.168.101.12', hostname: 'app2' }
    - { ip: '192.168.101.13', hostname: 'proxy' }

